# Generated by Django 3.2.22 on 2024-02-16 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelogue_app', '0002_remove_review_photo2'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lati',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='longi',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
